# Generated by Django 5.2.17 on 2026-09-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatthread',
            new_name='chat_chatth_user_id_d83b7d_idx',
            old_name='chat_chatt_us_4e5d3d_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_thread__9895ae_idx',
            old_name='chat_messa_threa_2ccf6a_idx',
        ),
    ]
